version: "3.9"
services:
  db:
    container_name: "library-db"
    image: postgres:13
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  api:
    container_name: "library-api"
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    environment:
      - "SECRET_KEY=django-insecure-..."
      - "DEBUG=True"
      - "FRONTEND_URL=http://localhost"
    # Expose port so we can see `django-debug-toolbar`:
    ports:
      - "8000:8000"
    depends_on:
      - db
  node:
      container_name: "library-node"
      build: ./frontend/
      command: node .output/server/index.mjs
      environment:
        - "NUXT_PUBLIC_API_BASE=http://localhost"
        - "NITRO_HOST=0.0.0.0"
        - "NITRO_PORT=3000"
  nginx:
    container_name: "library-nginx"
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - ./backend:/code
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/media:/media
      - ./backend/staticfiles:/staticfiles
    depends_on:
      - api
      - node