# Generated by Django 4.2 on 2023-05-01 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="имя"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="отчетство"
                    ),
                ),
                ("last_name", models.CharField(max_length=32, verbose_name="фамилия")),
            ],
            options={
                "verbose_name": "автор",
                "verbose_name_plural": "авторы",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="название")),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="год издания"
                    ),
                ),
                (
                    "contents",
                    models.TextField(
                        default=None, null=True, verbose_name="содержание"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/covers/",
                        verbose_name="обложка",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="books/",
                        verbose_name="файл книги",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.author",
                        verbose_name="автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "книга",
                "verbose_name_plural": "книги",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="название")),
            ],
            options={
                "verbose_name": "издательство",
                "verbose_name_plural": "издательства",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="название")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "метка",
                "verbose_name_plural": "метки",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="заметка")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="books.book",
                        verbose_name="книга",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "заметка",
                "verbose_name_plural": "заметки",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.publisher",
                verbose_name="идательство",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="books.tag", verbose_name="метки"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
