# Generated by Django 4.2 on 2023-05-01 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="contents",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="содержание"
            ),
        ),
        migrations.CreateModel(
            name="BookCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="прочитана"),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="избранная"),
                ),
                (
                    "read_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата прочтения"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_cards",
                        to="books.book",
                        verbose_name="книга",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "карточка книги",
                "verbose_name_plural": "карточки книг",
                "ordering": ["-created"],
            },
        ),
    ]
