# Generated by Django 4.2 on 2023-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_contents_bookcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcard",
            name="want_to_read",
            field=models.BooleanField(default=False, verbose_name="хочу прочитать"),
        ),
    ]
