# Generated by Django 4.2 on 2023-05-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_bookcard_want_to_read"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="profile_image",
            new_name="cover_image",
        ),
    ]
