# Generated by Django 4.2 on 2023-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_rename_profile_image_book_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books", to="books.author", verbose_name="авторы"
            ),
        ),
    ]
