# Generated by Django 4.2 on 2023-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_remove_book_author_book_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcard",
            name="is_reading",
            field=models.BooleanField(default=False, verbose_name="читаю сейчас"),
        ),
    ]
