# Generated by Django 4.2 on 2023-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="описание"
            ),
        ),
    ]
