# https://www.hacksoft.io/blog/github-actions-in-action-setting-up-django-and-postgres
name: Django Tests

on: [push]

jobs:
  build:
    name: Run Tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run migrations
      run: python manage.py backend/migrate
    - name: Run tests
      run: python manage.py backend/test